.DELETE_ON_ERROR:

self := $(lastword $(MAKEFILE_LIST))
GO ?= go
PROFILE_NAME ?= cover.out
DEPTEST ?= $(GO) run github.com/Warashi/deptest/cmd/deptest@latest
GOCOVMERGE ?= $(GO) run github.com/wadey/gocovmerge@latest

MODULE := $(shell $(GO) list -m)
PACKAGES := $(sort $(shell $(GO) list ./...))
PROFILES := $(patsubst $(MODULE)/%,%/$(PROFILE_NAME),$(PACKAGES))

.PHONY: all
all: $(PROFILE_NAME)

.PHONY: update-testdeps
update-testdeps:
	$(DEPTEST) -module $(MODULE) $(PROFILES) > $(self).tmp
	mv $(self).tmp $(self)

.PHONY: clean
clean:
	rm -f $(PROFILES)

$(PROFILE_NAME): $(PROFILES)
	$(GOCOVMERGE) $(PROFILES) > $(PROFILE_NAME)

$(PROFILES): %/$(PROFILE_NAME):
	$(GO) test -covermode=atomic -coverpkg=./... -coverprofile=./$@ ./$(dir $@)
{{ range . }}
{{ .Profile }}: {{ range .Deps }}{{.}} {{ end -}}
{{ end }}
